make IANA reference for Signature Schemes more precise
mlswg/mls-protocol pull request #415
Opened 2020-10-08 20:52 UTC by kkohbrok

Thanks @Bren2010 pointing out the imprecision. Is this what you were looking for?

Thanks @bifurcation for the pointer to the correct registry.

2020-10-09 14:34 UTC, Bren2010 commented
This doesn't make sense because we don't actually use this registry. The signature scheme is defined by the ciphersuite, and the ciphersuite registry doesn't map to this unrelated registry

2020-10-09 14:53 UTC, kkohbrok commented
The `SignatureScheme` is not authoritative in the group context and will always correspond with the one in the group (as is required by the generic description of the functionalities that Credentials have to provide). The SignatureScheme is there for when the Credential is handled in a context where there is no surrounding group. For example, when it's handled by the AS.

There is a mapping from ciphersuit to SignatureScheme in Table 5, the entries of which correspond to the entries in the referenced registry. Is that what you meant?

2020-10-09 22:25 UTC, Bren2010 requested changes

2020-10-09 22:25 UTC, Bren2010 commented on draft-ietf-mls-protocol.md
> +// See See RFC 8446 and the IANA TLS SignatureScheme registry
```suggestion
// See RFC 8446 and the IANA TLS SignatureScheme registry
```

2020-10-12 12:29 UTC, bifurcation approved these changes

2020-10-12 15:41 UTC, Bren2010 approved these changes

2020-10-19 14:11 UTC, merged