Remove some stale OPEN ISSUEs
mlswg/mls-protocol pull request #438
Opened 2020-11-16 17:08 UTC by bifurcation

In preparation for feature-freeze / post-first-WGLC living, this PR removes a few issues that have been discussed and pretty much resolved.  It leaves a few OPEN ISSUES that could benefit from analysis during the feature freeze.

2020-11-16 17:37 UTC, Bren2010 approved these changes

2020-11-18 16:55 UTC, raphaelrobert requested changes
Looks good in general. I flagged one issue I saw.

2020-11-18 16:55 UTC, raphaelrobert commented on draft-ietf-mls-protocol.md
> -
I'm inclined to have this documented somewhere, perhaps not as an open issue. Otherwise someone will claim they discovered an "attack".

2020-11-21 14:50 UTC, raphaelrobert approved these changes

2020-11-21 20:02 UTC, merged