Make ratchet tree section clearer.
mlswg/mls-protocol pull request #462
Opened 2021-03-08 06:00 UTC by Bren2010

2021-05-26 15:40 UTC, seanturner commented
202105 Interim: To be reviewed by editors.

2021-08-10 23:38 UTC, bifurcation requested changes
One minor fix, otherwise ready to go.

2021-08-10 23:38 UTC, bifurcation commented on draft-ietf-mls-protocol.md
> +keys for intermediate nodes in the direct path of its leaf. The
```suggestion
containing a set of public keys and encrypted path secrets
for intermediate nodes in the direct path of its leaf. The
```

2021-10-01 15:21 UTC, raphaelrobert approved these changes

2021-10-04 14:20 UTC, seanturner commented on draft-ietf-mls-protocol.md
> +keys for intermediate nodes in the direct path of its leaf. The
minor correctness fix.

2021-10-04 17:31 UTC, bifurcation approved these changes

2021-10-04 17:32 UTC, merged