Ensure that a signature public key is always intelligible
mlswg/mls-protocol pull request #637
Opened 2022-04-28 13:58 UTC by bifurcation

This PR moves the signature key from `Credential` to `LeafNode`, to ensure that an MLS client always has a signature public key with which to verify messages, even if it does not support a member's credential type.

This is an alternative approach to #628, and IMO a bit cleaner.  We no longer need the notion of a SignatureScheme, since BasicCredential doesn't stand alone.  And since Credential only appears in LeafNode, common fields can be hoisted up into LeafNode. The Credential struct really only exists as a conceptual boundary, to make the exposition clearer; otherwise you could just shove the `select` into LeafNode.

Note that this does not obviate the need for #631.  This PR only ensures that the signatures can be processed; that PR helps ensure that the signatures are meaningful.

2022-04-29 06:16 UTC, kkohbrok requested changes
Can you elaborate on why we need this if we also mandate that all clients have to support the credential types of all other clients? I would think that if a client supports a credential type, it knows how to extract the signature public key from that credential.

2022-04-29 06:16 UTC, kkohbrok commented on draft-ietf-mls-protocol.md
> +applciation to decide which identifier or identifiers to use at the application
```suggestion
application to decide which identifier or identifiers to use at the application
```

2022-04-29 17:50 UTC, bifurcation commented
@kkohbrok - As I noted in the intro comment, I think you can view these two PRs as addressing different levels of interop -- the mechanics of verifying signatures vs. the ability to actually meaningfully interpret a credential.  Always having the key in the same place could also allow some minor simplification to implementation logic

It's also interesting to consider what this would imply for future credential types.  On the one hand, they wouldn't need to recite the public key, just provide a binding to it, like a hash or a signature where the public key was filled in from outside.  On the other hand, it would open up the door to credential types that aren't actually bound to the public key, which creates replay risk.

In any case, as the above might hint, I don't have strong feelings about this.  I mainly wanted to present an alternative to #628 that was more palatable to me.  Given the replay risk noted above, though, I think I'm trending toward closing both this PR and #628, and just keeping the current structure with the improved compatibilty bounds provided by #631.

2022-05-02 18:14 UTC, rohan-wire approved these changes

2022-05-02 18:14 UTC, bifurcation commented
Latest commit responds to some offline comments from @rohan-wire: 

* Having `public_key` and `signature_key` makes it a little confusing what `public_key` is about.  So changed to `encryption_key` and propagated that change throughout.
* The definition of `SignaturePublicKey` fits better in the ciphersuites section (next to `HPKEPublicKey`) than it does in the credentials section

Having done that, I'm more positive on this change.  The `encryption_key` change is a good clarification, and having the signature public key separate from the credential provides a stonger decoupling of the credential from the MLS crypto. The only thing the credential layer needs to know now is how to bind to the signature key.

2022-05-02 18:21 UTC, merged