Remove "MLS" prefix on structs
mlswg/mls-protocol pull request #839
Opened 2022-12-15 16:51 UTC by bifurcation

Fixes #759 

As discussed in #759, this PR makes the following terminology changes:

| Before                      | After                     |
|:----------------------------|:--------------------------|
| MLSMessage                  | MLSMessage                |
| MLSContent                  | GroupContent              |
| MLSContentTBS               | GroupContentTBS           |
| MLSContentAuthData          | GroupContentAuthData      |
| MLSAuthenticatedContent     | AuthenticatedContent      |
| MLSContentTBM               | AuthenticatedContentTBM   |
| MLSSenderData               | SenderData                |
| MLSSenderDataAAD            | SenderDataAAD             |
| MLSCiphertextContent        | AuthenticatedContentTBE   |
| MLSCiphertextContentAAD     | ContentAAD                |
| MLSPlaintext                | PublicMessage             |
| MLSCiphertext               | PrivateMessage            |

It might be useful to review the two commits here separately.  The first is just a global search-and-replace.  The second is a light review for grammar ("a" vs. "an"), and makes a few small copy edits.

2022-12-15 19:46 UTC, duesee reviewed
Thanks for tackling this, @bifurcation! I hope to help a bit with a review.

I grepped for the old names ...

```sh
for name_before in MLSContent MLSContentTBS MLSContentAuthData MLSAuthenticatedContent MLSContentTBM MLSSenderData MLSSenderDataAAD MLSCiphertextContent MLSCiphertextContentAAD MLSPlaintext MLSCiphertext; do echo Checking $name_before; rg -i $name_before; done
Checking MLSContent
Checking MLSContentTBS
Checking MLSContentAuthData
Checking MLSAuthenticatedContent
Checking MLSContentTBM
Checking MLSSenderData
Checking MLSSenderDataAAD
Checking MLSCiphertextContent
Checking MLSCiphertextContentAAD
Checking MLSPlaintext
draft-ietf-mls-protocol.md
355:- Handle non-member sender cases in MLSPlaintextTBS
395:- Move MLSPlaintext signature under the confirmation tag (\*)
397:- Explicitly authenticate group membership with MLSPLaintext (\*)
458:- Allow multiple Proposals and a single Commit in one MLSPlaintext (\*)
481:- Cover the entire MLSPlaintext in the transcript hash (\*)
Checking MLSCiphertext
```

... and verified that the remaining instances of `MLSPlaintext` are all in the `##  Change Log` section. Furthermore, I checked that no accidental renames were made to this section.

I couldn't find any (grammatical or visual) mistakes in the second commit. Also, doing some spot-checks for the first commit, I couldn't find anything wrong either.

So, it all looks excellent to me :+1:

2022-12-16 07:44 UTC, kkohbrok commented on draft-ietf-mls-protocol.md
> +    select (GroupContent.content_type) {
I suggested "MessageContent", "MessageContentTBS", etc. as opposed to using the "Group-" prefix. It got some 👍🏻, but no other reaction. Do you still prefer the "Group-" prefix?

2022-12-16 09:34 UTC, raphaelrobert approved these changes

2022-12-16 09:52 UTC, beurdouche requested changes
I agree with Konrad that GroupContent is very weird. Here is a proposal `FrameContent`.

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +    select (GroupContent.content_type) {
```suggestion
    select (FrameContent.content_type) {
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +} GroupContent;
```suggestion
} FrameContent;
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +    GroupContentAuthData auth;
```suggestion
    FrameContent content;
    FrameContentAuthData auth;
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +                                         GroupContent
```suggestion
                                         FrameContent
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +                           GroupContentAuthData |                  |   Sign / Verify
```suggestion
                           FrameContentAuthData |                  |   Sign / Verify
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +GroupContent is authenticated using the GroupContentAuthData structure.
```suggestion
FrameContent is authenticated using the FrameContentAuthData structure.
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +    select (GroupContentTBS.content.sender.sender_type) {
```suggestion
    FrameContent content;
    select (FrameContentTBS.content.sender.sender_type) {
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +} GroupContentTBS;
```suggestion
} FrameContentTBS;
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +    /* SignWithLabel(., "GroupContentTBS", GroupContentTBS) */
```suggestion
    /* SignWithLabel(., "FrameContentTBS", FrameContentTBS) */
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +    select (GroupContent.content_type) {
```suggestion
    select (FrameContent.content_type) {
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +} GroupContentAuthData;
```suggestion
} FrameContentAuthData;
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +`"GroupContentTBS"` and with a content that covers the message content and
```suggestion
`"FrameContentTBS"` and with a content that covers the message content and
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +at the same state of the group. A GroupContentAuthData is said to be valid when both
```suggestion
at the same state of the group. A FrameContentAuthData is said to be valid when both
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +    GroupContentAuthData auth;
```suggestion
    FrameContent content;
    FrameContentAuthData auth;
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +GroupContentAuthData is valid.
```suggestion
FrameContentAuthData is valid.
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +    GroupContentAuthData auth;
```suggestion
    FrameContentAuthData auth;
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +GroupContentAuthData is valid.
```suggestion
FrameContentAuthData is valid.
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +    GroupContent content; /* with content_type == commit */
```suggestion
    FrameContent content; /* with content_type == commit */
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +Proposals are included in a GroupContent by way of a Proposal structure
```suggestion
Proposals are included in a FrameContent by way of a Proposal structure
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +On receiving a GroupContent containing a Proposal, a client MUST verify the
```suggestion
On receiving a FrameContent containing a Proposal, a client MUST verify the
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +GroupContent is equal to the `epoch` field of the current GroupContext object.
```suggestion
signature inside FrameContentAuthData and that the `epoch` field of the enclosing
FrameContent is equal to the `epoch` field of the current GroupContext object.
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +  * Use the GroupContent to update the confirmed transcript hash and update
```suggestion
* Construct a FrameContent object containing the Commit object. Sign the
  FrameContent using the old GroupContext as context.
  * Use the FrameContent to update the confirmed transcript hash and update
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +    hash and the `confirmation_tag` from the GroupContentAuthData.
```suggestion
    hash and the `confirmation_tag` from the FrameContentAuthData.
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +  * The confirmation_tag from the GroupContentAuthData object
```suggestion
  * The confirmation_tag from the FrameContentAuthData object
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +* Verify that the `epoch` field of the enclosing GroupContent is equal
```suggestion
* Verify that the `epoch` field of the enclosing FrameContent is equal
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +* Verify that the signature on the GroupContent message as described in
```suggestion
* Verify that the signature on the FrameContent message as described in
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +  `confirmation_tag` field in the GroupContentAuthData object.
```suggestion
  `confirmation_tag` field in the FrameContentAuthData object.
```

2022-12-16 09:52 UTC, beurdouche commented on draft-ietf-mls-protocol.md
> +indicated by the `epoch` field of the enclosing GroupContent.
```suggestion
indicated by the `epoch` field of the enclosing FrameContent.
```

2022-12-16 17:20 UTC, bifurcation commented
As discussed in the interim 2022-12-16:
* Keeping Public/Private
* GroupContent -> FramedContent
* ContentAAD -> PrivateContentAAD
* I also added: AuthenticatedContentTBE -> PrivateContentTBE (to be parallel with PrivateContentAAD)

2022-12-16 17:20 UTC, merged

2023-02-14 11:17 UTC, TWal commented
For anyone wondering, here are the final changes made by this PR.

| Before                   | After                      |
| ------------------------ | -------------------------- |
| MLSMessage               | MLSMessage                 |
| MLSContent               | FramedContent              |
| MLSContentTBS            | FramedContentTBS           |
| MLSContentAuthData       | FramedContentAuthData      |
| MLSAuthenticatedContent  | AuthenticatedContent       |
| MLSContentTBM            | AuthenticatedContentTBM    |
| MLSSenderData            | SenderData                 |
| MLSSenderDataAAD         | SenderDataAAD              |
| MLSCiphertextContent     | PrivateContentTBE          |
| MLSCiphertextContentAAD  | PrivateContentAAD          |
| MLSPlaintext             | PublicMessage              |
| MLSCiphertext            | PrivateMessage             |

Which makes me wonder: since `SenderData` is only meant to be encrypted, shouldn't it be `SenderDataTBE`?