IESG Review from Éric Vyncke
mlswg/mls-protocol pull request #853
Opened 2023-02-02 16:42 UTC by bifurcation

https://datatracker.ietf.org/iesg/agenda/#draft-ietf-mls-protocol_eric-vyncke

2023-02-02 16:55 UTC, raphaelrobert approved these changes

2023-02-03 07:02 UTC, kkohbrok requested changes

2023-02-03 07:02 UTC, kkohbrok commented on draft-ietf-mls-protocol.md
> +{: title="Initialization of the hash ratches from the leaves of a secret tree" }
```suggestion
{: title="Initialization of the hash ratchets from the leaves of a secret tree" }
```

2023-02-07 17:18 UTC, kkohbrok approved these changes

2023-02-09 19:11 UTC, merged